project:
  type: book
  output-dir: docs

book:
  title: "Exploratory Data Analysis for Ecologists and Biologists"
  author: "Thiyanga S. Talagala"
  date: "4/17/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - ch1.qmd
    - ch2.qmd
    - ch3.qmd
    - ch4.qmd
    - ch5.qmd
    - ch6.qmd
    - ch7.qmd
    - ch8.qmd
    - ch9.qmd
    - ch10.qmd
    - ch11.qmd
    - ch12.qmd
    - ch13.qmd
    - ch14.qmd
    - references.qmd
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



